name: arrow
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.30.1
  cupertino_icons: ^1.0.8
  flame_forge2d: ^0.15.0  # Fizik motoru (opsiyonel)
  shared_preferences: ^2.5.3
  flame_audio: ^2.1.7  # Ses için eklendi


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
